language: python
before_install: cd backend
script: echo 'Not running tests'
#before_deploy: cd backend
deploy:
  provider: heroku
  api_key:
    secure: MMi/2KcyXHRMQDVdOE4drxA50Gkxw6o52j2R8rNI/T+runoN8NCfbhmryeRLL58YHHQ6udG1iUeEajqEqrf/cHTLs+GzHHbhisCY5o0wwInisxENFC4ESeDQ9bFTkFdbgyGZjtFslVKKI9YhrvhSlCOm5N3UjgTmiitx1Ug6c1P7k6/37Htu/3QeYkqOb1Avh9791DJrutbymxHbReLIWqg/U0iquGK0SeOYWWmaKAKeY4BM6trMkbKfe//LGtLXHK0uyt0BxedPfTK8Kvdk4Usgh0TuCqVMhtTE1Fe1X0sLxrc0SbjoCX28dsh4N1MgQC9KPejb8gYN8he6LBQXe5tA3FuZGoQqQAgwGr3o6I6XQH9E+D7W71qmu1jy18UWiD//HpaHI70NdhmyakUX17lbiOqDkMHVLnnrNmQjDIKklVXM5I3nTxnwYc0wEk6t5+LAI7+PH/xX6geHQN4LKekrDWm2TWM01jBDwxqTQEWftd6hCa8t7CyyUK8XIsWwb7VRhjygVbd5tQ6DsTLBkkTuZujQPuScBxJAHY2ebEbVeSCJm2QpvbcRD5U+azQPX5UN0H4ZFxO4RpsQKrNKNHLjzR5ATxtMHQzNlUksDkfAA0bGG8PcwTCOpwuLcca0o+h5SUVWmGZB8oZyM6Fl4PoxpA7P9mnWij3++CCt9jc=
  app: warm-plateau-64202
